CREATE TABLE burnban_requests (
    schema_version VARCHAR(64) NOT NULL,
    request_id BIGINT NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    provider VARCHAR(256) NOT NULL,
    model VARCHAR(256),
    agent VARCHAR(256),
    route VARCHAR(256),
    service_tier VARCHAR(256),
    geo VARCHAR(256),
    principal VARCHAR(256),
    trusted_principal VARCHAR(256),
    service_account VARCHAR(256),
    identity_tenant VARCHAR(256),
    project VARCHAR(256),
    cost_center VARCHAR(256),
    identity_device_id VARCHAR(256),
    identity_confidence VARCHAR(32) NOT NULL,
    input_tokens BIGINT NOT NULL,
    output_tokens BIGINT NOT NULL,
    cache_read_tokens BIGINT NOT NULL,
    cache_write_tokens BIGINT NOT NULL,
    cache_write_1h_tokens BIGINT NOT NULL,
    cost_usd DECIMAL(24, 12) NOT NULL,
    latency_ms BIGINT NOT NULL,
    http_status INTEGER NOT NULL,
    streamed BOOLEAN NOT NULL,
    usage_confidence VARCHAR(32) NOT NULL,
    pricing_state VARCHAR(32) NOT NULL,
    cost_source VARCHAR(64),
    cost_source_ref VARCHAR(256),
    cost_effective_from TIMESTAMP,
    cost_valid_through TIMESTAMP,
    cost_confidence VARCHAR(64),
    incomplete BOOLEAN NOT NULL,
    enforcement_gap BOOLEAN NOT NULL,
    decision_id BIGINT,
    decision VARCHAR(64),
    decision_admitted BOOLEAN,
    policy_name VARCHAR(256),
    policy_namespace VARCHAR(256),
    policy_version BIGINT,
    policy_digest VARCHAR(64),
    policy_mode VARCHAR(32),
    policy_confidence VARCHAR(32),
    retry_count BIGINT NOT NULL,
    downshifted BOOLEAN NOT NULL,
    downshift_from VARCHAR(256),
    requested_provider VARCHAR(256),
    requested_route VARCHAR(256),
    downshift_action VARCHAR(32),
    downshift_rule VARCHAR(256),
    downshift_trigger VARCHAR(64),
    downshift_reason VARCHAR(256),
    downshift_config_digest VARCHAR(64),
    downshift_source_estimated_usd DECIMAL(24, 12),
    downshift_target_estimated_usd DECIMAL(24, 12)
);
